spring:
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: 192.168.0.186:8848
  #        # 指定namespace（隔离环境:pre,dev等）
  #        namespace: 56116141-d837-4d15-8842-94e153bb6cfb
  #        # 指定集群名称（可以优先地域访问：比如说北京和南京部署了同一集群名称，北京地区的优先访问,如果北京服务宕机，才会访问南京的服务）
  #        cluster-name: BJ
  #        #元数据信息(可以指定多个版本间，同一版本服务访问)
  #        metadata:
  #          instance: c
  #          haha: hehe
  #          version: v1
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: user-consume
server:
  port: 8050


#指定访问服务的路由策略(局部); 默认不配置是轮询策略
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.liwen.demo.config.RibbonConfiguration

##配置指定访问服务使用饥饿加载：访问多个服务名用逗号隔开
##默认是懒加载：即访问的时候才创建，所以默认第一次访问相对慢一点
#ribbon:
#  eager-load:
#    clients: user-service
