spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud-seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8082
